# Schema for configuration files of the PHP FFMpeg module.

php_ffmpeg.settings:
  type: config_object
  label: 'PHP FFMpeg settings'
  mapping:
    php_ffmpeg_ffmpeg_binary:
      type: string
      label: 'Path to the ffmpeg binary.'
    php_ffmpeg_ffprobe_binary:
      type: string
      label: 'Path to the ffprobe binary.'
    php_ffmpeg_timeout:
      type: integer
      label: 'Timeout for ffmpeg/ffprobe command execution in seconds. Leave empty for none.'
    php_ffmpeg_threads:
      type: integer
      label: 'Number of threads to use for ffmpeg commands.'
    php_ffmpeg_monolog_channel:
      type: string
      label: 'The monolog channel to use for logging.'
